### ISSUE TITLE
Test on Asus X555L

### ISSUE THREAD

**Issue by olympiabrown** [raspberrypilearning/install-raspberry-pi-desktop#4]
I'm testing this resource on the Code Club laptops, which are Asus X555L. According to the list, the boot key should be F8. However, this didn't do anything. Instead, I found this option in the start menu. 
![img_20181003_105621](https://user-images.githubusercontent.com/23454369/46404180-59799a80-c6fc-11e8-8f92-cfa2a4762106.jpg)

this then takes me to
![img_20181003_105907](https://user-images.githubusercontent.com/23454369/46404199-66968980-c6fc-11e8-8a80-e509ae715c6d.jpg)

then
![img_20181003_105915](https://user-images.githubusercontent.com/23454369/46404202-6ac2a700-c6fc-11e8-875c-2b41fe2eca7b.jpg)

but finally, I get this error message
![img_20181003_105936](https://user-images.githubusercontent.com/23454369/46404223-744c0f00-c6fc-11e8-98f6-fcf288180353.jpg)

**Comment by martinohanlon** [comment]
Thanks @olympiabrown 

A well raised issue,thank you :)

I think the solution would be to enter your BIOS and disable "Secure boot". Although the instructions on how to do that will be specific for your computer.  Fancy having a go?

You are unlikely to be the only one who experiences this issue so I will have a think about how we can provide some "guidelines" for how someone might "disable secure boot"

**Comment by olympiabrown** [comment]
Oooh ok I did some more searching round, and there's lots of confusing information. *But* it did give me an alternative key to try for entering the boot menu, so trying that. I'll keep you posted

**Comment by martinohanlon** [comment]
There is a video here which describes how to setup the bios on an x555l https://www.youtube.com/watch?v=vVraydLORf4

**Comment by olympiabrown** [comment]
I found the setting! I'm in!!!

**Comment by martinohanlon** [comment]
Nice work.

**Comment by olympiabrown** [comment]
OK, it all works (yay!). Only comment on the resource itself is that where you say 'select which disk to partition, there'll only be one' - I actually had two
![img_20181003_112402](https://user-images.githubusercontent.com/23454369/46405331-d8bc9d80-c6ff-11e8-8924-e96d7ffb56c4.jpg)

I selected the top one as it was larger....

**Comment by martinohanlon** [comment]
Interesting...  It looks likes the bios on this laptop shows your usb stick as well as the hard drive.  With the laptops I tested with, it hid the usb stick as your were currently booting from it.

You made the right choice.

Ill include some instructions about "which drive to pick", if there are more than one.

**Comment by olympiabrown** [comment]
I couldn't connect to the internet when finishing up, so haven't done the Raspbian update. Maybe include a drop down box thing to show how to do that later if you don't have internet where you are installing?

Also (asking for a friend) maybe some guidance about whether you need to keep the USB drive in the computer after you've successfully set up, or if you can remove it after that

**Comment by martinohanlon** [comment]
Thanks @olympiabrown :)

**Comment by martinohanlon** [comment]
@olympiabrown no you dont need to keep the usb drive in the computer after you have installed Raspbian. I will put a step in to remove it when the install has finished.

**Comment by olympiabrown** [comment]
Proper pleased with myself for doing this. Thanks Martin, v clear instructions. Can see there's likely to be quite a few problems with the specifics of people's computers, but the bits there are a v clear

**Comment by martinohanlon** [comment]
Updates made in draft
