### ISSUE TITLE
Installing Debian Linux section

### ISSUE THREAD

**Issue by m-bowley** [raspberrypilearning/install-raspberry-pi-desktop#6]
In the fourth section, titled "Run the Installation" it switches from talking about installing the Raspberry Pi Desktop to installing Debian Linux. Thought this could be made more continuous by switching these back to RPi Desktop. I almost expected there to be another step.

**Comment by martinohanlon** [comment]
Thanks, I have split step 4 into 2 and renamed the sections as there was a lack of "flow". Hopefully this improves it.
